services:
  discord-bot:
    build: .
    container_name: homelab-discord-bot
    restart: unless-stopped
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
    group_add:
      - "1001"
    networks:
      - homelab

networks:
  homelab:
    driver: bridge